#!/usr/bin/env bash
# Generated by Cursor
# post-ci-diagnose.sh — Post diagnosis comment and optionally re-run flaky checks.
#
# Runs on the trusted runner after sandbox exit. Side effects (comments, retries)
# happen here — never inside the sandbox.
#
# Required env:
#   REPO_FULL_NAME   — owner/repo (set by dispatch)
#   GH_TOKEN         — GitHub token with pull-requests:write and actions:write
#   GITHUB_ISSUE_URL — issue or PR URL (set by dispatch or caller).
#                      `gh pr comment` and `gh pr view` accept the URL.
#                      A numeric id is extracted for REST and
#                      `fullsend post-comment --number`.
#
#   MAX_FLAKE_RETRIES      — max automatic flake retries (set by harness yaml)
#   MIN_RETRY_CONFIDENCE   — minimum confidence to retry (set by harness yaml)
#   CHECK_CONTEXT_FILE     — pre-script context (set by harness yaml)
#
#   FULLSEND_OUTPUT_FILE   — result filename (set by harness yaml)
#
# Optional env:
set -euo pipefail

# Marker used by fullsend post-comment to upsert a sticky diagnosis comment.
COMMENT_MARKER='<!-- fullsend:ci-diagnose -->'
RESULT_NAME="${FULLSEND_OUTPUT_FILE}"

# Numeric id for REST paths and `fullsend post-comment --number`.
pr_number_from_url() {
  local url="${GITHUB_ISSUE_URL}"
  if [[ "${url}" =~ /(issues|pull)/([0-9]+) ]]; then
    printf '%s' "${BASH_REMATCH[2]}"
    return 0
  fi
  echo "::error::GITHUB_ISSUE_URL has no issue/PR number: ${url}"
  exit 1
}

# Locate the agent's diagnosis JSON.
find_result_file() {
  local candidate
  for candidate in \
    ${FULLSEND_VALIDATED_ITERATION_DIR:+"${FULLSEND_VALIDATED_ITERATION_DIR}/output/${RESULT_NAME}"} \
    iteration-*/output/"${RESULT_NAME}"
  do
    [[ -f "${candidate}" ]] && { printf '%s' "${candidate}"; return 0; }
  done
  echo "::error::Result file ${RESULT_NAME} not found"
  exit 1
}

# Per-check retries map from pre-script context: {"check_name": count, …}.
read_retries_map_from_context() {
  local context_file="${CHECK_CONTEXT_FILE}"
  if [[ -f "${context_file}" ]]; then
    jq '
      .retry_budget.per_check // {}
      | to_entries
      | map({key: .key, value: (.value.retries_used // 0)})
      | from_entries
    ' "${context_file}" 2>/dev/null || printf '{}'
  else
    printf '{}'
  fi
}

# HEAD SHA from pre-script context (needed for per-check retry markers).
read_head_sha_from_context() {
  local context_file="${CHECK_CONTEXT_FILE}"
  if [[ -f "${context_file}" ]]; then
    jq -r '.head_sha // ""' "${context_file}" 2>/dev/null || printf ''
  else
    printf ''
  fi
}

# True when the agent recommends a flake retry and confidence qualifies.
# Per-check budget enforcement happens in rerequest_targets.
should_retry() {
  local result_file="$1"
  local min_confidence="${MIN_RETRY_CONFIDENCE}"

  jq -e \
    --argjson min_confidence "${min_confidence}" '
      .recommended_action == "retry"
      and .classification == "flaky"
      and (.confidence >= $min_confidence)
      and ((.retry_targets | length) > 0)
    ' "${result_file}" >/dev/null 2>&1
}

# Post a sticky diagnosis comment via fullsend post-comment.
post_sticky_comment() {
  local body_file="$1"
  export GITHUB_TOKEN="${GH_TOKEN}"
  fullsend post-comment \
    --repo "${REPO_FULL_NAME}" \
    --number "$(pr_number_from_url)" \
    --marker "${COMMENT_MARKER}" \
    --token "${GH_TOKEN}" \
    --result "${body_file}"
}

# Re-run each job listed in retry_targets that still has per-check budget.
# Prints successfully retried check names to stdout (one per line).
# Returns 0 if at least one re-run succeeded, 1 otherwise.
rerequest_targets() {
  local result_file="$1"
  local retries_map="$2"
  local max_retries="${MAX_FLAKE_RETRIES}"
  local id name used err_output
  local ok_count=0
  local fail_count=0
  local skip_count=0

  while IFS=$'\t' read -r id name; do
    if [[ -z "${id}" || "${id}" == "null" ]]; then
      echo "::warning::Skipping retry target without check_run_id: ${name}" >&2
      fail_count=$((fail_count + 1))
      continue
    fi
    used="$(printf '%s' "${retries_map}" | jq -r --arg n "${name}" '.[$n] // 0')"
    if [[ "${used}" -ge "${max_retries}" ]]; then
      echo "::notice::Skipping ${name}: budget exhausted (${used}/${max_retries})" >&2
      skip_count=$((skip_count + 1))
      continue
    fi
    echo "::notice::Re-running job ${id} (${name})" >&2
    if err_output="$(gh api -X POST "repos/${REPO_FULL_NAME}/actions/jobs/${id}/rerun" 2>&1)"; then
      ok_count=$((ok_count + 1))
      printf '%s\n' "${name}"
    else
      echo "::warning::Failed to re-run job ${id} (${name}): ${err_output}" >&2
      fail_count=$((fail_count + 1))
    fi
  done < <(jq -r '.retry_targets[] | [((.check_run_id // "null")|tostring), .check_name] | @tsv' "${result_file}")

  echo "::notice::Retry summary: ok=${ok_count} failed=${fail_count} skipped=${skip_count}" >&2
  [[ "${ok_count}" -gt 0 ]]
}

main() {
  command -v gh >/dev/null || { echo "::error::gh not found"; exit 1; }
  command -v jq >/dev/null || { echo "::error::jq not found"; exit 1; }
  : "${REPO_FULL_NAME:?Required env REPO_FULL_NAME is not set}"
  : "${GH_TOKEN:?Required env GH_TOKEN is not set}"
  : "${GITHUB_ISSUE_URL:?Required env GITHUB_ISSUE_URL is not set}"
  : "${CHECK_CONTEXT_FILE:?Required env CHECK_CONTEXT_FILE is not set}"
  : "${MAX_FLAKE_RETRIES:?Required env MAX_FLAKE_RETRIES is not set}"
  : "${MIN_RETRY_CONFIDENCE:?Required env MIN_RETRY_CONFIDENCE is not set}"
  : "${FULLSEND_OUTPUT_FILE:?Required env FULLSEND_OUTPUT_FILE is not set}"
  export GH_TOKEN

  # 1) Load and validate agent output
  local result_file did_retry retry_note body_file
  result_file="$(find_result_file)"
  echo "::notice::Reading diagnosis result from ${result_file}"

  if ! jq empty "${result_file}" >/dev/null 2>&1; then
    echo "::error::Result is not valid JSON: ${result_file}"
    exit 1
  fi

  # 2) Decide whether to re-request flaky checks (trusted side effects only).
  #    Budget is per-check and scoped to HEAD SHA.
  local retries_map head_sha retried_checks
  retries_map="$(read_retries_map_from_context)"
  head_sha="$(read_head_sha_from_context)"

  did_retry="false"
  retry_note=""
  retried_checks=""

  if should_retry "${result_file}"; then
    if retried_checks="$(rerequest_targets "${result_file}" "${retries_map}")"; then
      did_retry="true"
      local retried_count
      retried_count="$(printf '%s\n' "${retried_checks}" | grep -c .)"
      retry_note="**Retry:** re-requested ${retried_count} flaky check run(s)."
    else
      retry_note="**Retry:** recommended, but no check runs could be re-requested."
    fi
  else
    local action classification
    action="$(jq -r '.recommended_action' "${result_file}")"
    classification="$(jq -r '.classification' "${result_file}")"
    if [[ "${action}" == "retry" ]]; then
      retry_note="**Retry:** skipped (classification=${classification}, min_confidence=${MIN_RETRY_CONFIDENCE})."
    fi
  fi

  # 3) Build and post sticky diagnosis comment with per-check retry markers
  local body
  body="$(jq -r '.pr_comment_markdown' "${result_file}")"
  if [[ -z "${body}" || "${body}" == "null" ]]; then
    echo "::error::Result missing pr_comment_markdown"
    exit 1
  fi

  body_file="$(mktemp)"
  {
    printf '%s\n' "${body}"
    [[ -n "${retry_note}" ]] && printf '\n---\n%s\n' "${retry_note}"
    if [[ -n "${retried_checks}" ]]; then
      local check_name old_count
      while IFS= read -r check_name; do
        [[ -z "${check_name}" ]] && continue
        old_count="$(printf '%s' "${retries_map}" | jq -r --arg n "${check_name}" '.[$n] // 0')"
        printf '<!-- fullsend:ci-diagnose-retries:%s:%s:%s -->\n' \
          "${check_name}" "${head_sha}" "$((old_count + 1))"
      done <<< "${retried_checks}"
    fi
  } >"${body_file}"
  echo "::notice::Posting diagnosis comment on ${GITHUB_ISSUE_URL}"
  post_sticky_comment "${body_file}"
  rm -f "${body_file}"
  echo "::notice::ci-diagnose post-script complete"
}

main "$@"
