#!/usr/bin/env bash
# Generated by Cursor
# post-ci-diagnose.sh — Post diagnosis comment and optionally re-run flaky checks.
#
# Runs on the trusted runner after sandbox exit. Side effects (comments, retries)
# happen here — never inside the sandbox.
#
# Required env:
#   REPO_FULL_NAME   — owner/repo (set by dispatch)
#   GH_TOKEN         — GitHub token with pull-requests:write and actions:write
#   GITHUB_ISSUE_URL — issue or PR URL (set by dispatch or caller).
#                      `gh pr comment` and `gh pr view` accept the URL.
#                      A numeric id is extracted for REST and
#                      `fullsend post-comment --number`.
#
#   MAX_FLAKE_RETRIES      — max automatic flake retries (set by harness yaml)
#   MIN_RETRY_CONFIDENCE   — minimum confidence to retry (set by harness yaml)
#   CHECK_CONTEXT_FILE     — pre-script context (set by harness yaml)
#
# Optional env:
#   FULLSEND_OUTPUT_FILE   — result filename (default: ci-diagnose-result.json)
set -euo pipefail

# Marker used by fullsend post-comment to upsert a sticky diagnosis comment.
COMMENT_MARKER='<!-- fullsend:ci-diagnose -->'
RESULT_NAME="${FULLSEND_OUTPUT_FILE:-ci-diagnose-result.json}"

# Numeric id for REST paths and `fullsend post-comment --number`.
pr_number_from_url() {
  local url="${GITHUB_ISSUE_URL}"
  if [[ "${url}" =~ /(issues|pull)/([0-9]+) ]]; then
    printf '%s' "${BASH_REMATCH[2]}"
    return 0
  fi
  echo "::error::GITHUB_ISSUE_URL has no issue/PR number: ${url}"
  exit 1
}

# Locate the agent's diagnosis JSON.
find_result_file() {
  local candidate
  for candidate in \
    ${FULLSEND_VALIDATED_ITERATION_DIR:+"${FULLSEND_VALIDATED_ITERATION_DIR}/output/${RESULT_NAME}"} \
    iteration-*/output/"${RESULT_NAME}"
  do
    [[ -f "${candidate}" ]] && { printf '%s' "${candidate}"; return 0; }
  done
  echo "::error::Result file ${RESULT_NAME} not found"
  exit 1
}

# retries_used from pre-script check-context.json (defaults to 0 if missing).
retries_used_from_context() {
  local context_file="${CHECK_CONTEXT_FILE}"
  local raw
  if [[ -f "${context_file}" ]]; then
    raw="$(jq -r '.retry_budget.retries_used // 0' "${context_file}" | tr -d '[:space:]')"
  fi
  if [[ "${raw:-}" =~ ^[0-9]+$ ]]; then
    printf '%s' "${raw}"
  else
    printf '0'
  fi
}

# True when the agent recommends a flake retry and budget/confidence allow it.
should_retry() {
  local result_file="$1"
  local retries_used="$2"
  local max_retries="${MAX_FLAKE_RETRIES}"
  local min_confidence="${MIN_RETRY_CONFIDENCE}"

  jq -e \
    --argjson retries_used "${retries_used}" \
    --argjson max_retries "${max_retries}" \
    --argjson min_confidence "${min_confidence}" '
      .recommended_action == "retry"
      and .classification == "flaky"
      and (.confidence >= $min_confidence)
      and ($retries_used < $max_retries)
      and ((.retry_targets | length) > 0)
    ' "${result_file}" >/dev/null 2>&1
}

# Post a sticky diagnosis comment via fullsend post-comment.
post_sticky_comment() {
  local body_file="$1"
  export GITHUB_TOKEN="${GH_TOKEN}"
  fullsend post-comment \
    --repo "${REPO_FULL_NAME}" \
    --number "$(pr_number_from_url)" \
    --marker "${COMMENT_MARKER}" \
    --token "${GH_TOKEN}" \
    --result "${body_file}"
}

# Re-run each job listed in retry_targets via the Actions API. The check_run_id
# for GitHub Actions jobs doubles as the job_id. Succeeds if at least one
# re-run works (partial success still counts as a retry attempt).
rerequest_targets() {
  local result_file="$1"
  local id name err_output
  local ok_count=0
  local fail_count=0

  while IFS=$'\t' read -r id name; do
    if [[ -z "${id}" || "${id}" == "null" ]]; then
      echo "::warning::Skipping retry target without check_run_id: ${name}"
      fail_count=$((fail_count + 1))
      continue
    fi
    echo "::notice::Re-running job ${id} (${name})"
    if err_output="$(gh api -X POST "repos/${REPO_FULL_NAME}/actions/jobs/${id}/rerun" 2>&1)"; then
      ok_count=$((ok_count + 1))
    else
      echo "::warning::Failed to re-run job ${id} (${name}): ${err_output}"
      fail_count=$((fail_count + 1))
    fi
  done < <(jq -r '.retry_targets[] | [((.check_run_id // "null")|tostring), .check_name] | @tsv' "${result_file}")

  echo "::notice::Retry summary: ok=${ok_count} failed=${fail_count}"
  if [[ "${ok_count}" -eq 0 ]]; then
    return 1
  fi
  return 0
}

main() {
  command -v gh >/dev/null || { echo "::error::gh not found"; exit 1; }
  command -v jq >/dev/null || { echo "::error::jq not found"; exit 1; }
  : "${REPO_FULL_NAME:?Required env REPO_FULL_NAME is not set}"
  : "${GH_TOKEN:?Required env GH_TOKEN is not set}"
  : "${GITHUB_ISSUE_URL:?Required env GITHUB_ISSUE_URL is not set}"
  export GH_TOKEN

  # 1) Load and validate agent output
  local result_file retries_used did_retry retry_note body_file
  result_file="$(find_result_file)"
  echo "::notice::Reading diagnosis result from ${result_file}"

  if ! jq empty "${result_file}" >/dev/null 2>&1; then
    echo "::error::Result is not valid JSON: ${result_file}"
    exit 1
  fi

  # 2) Decide whether to re-request flaky checks (trusted side effects only)
  retries_used="$(retries_used_from_context)"

  did_retry="false"
  retry_note=""

  if should_retry "${result_file}" "${retries_used}"; then
    if rerequest_targets "${result_file}"; then
      did_retry="true"
      retry_note="**Retry:** re-requested flaky check run(s) (attempt $((retries_used + 1))/${MAX_FLAKE_RETRIES})."
    else
      retry_note="**Retry:** recommended, but no check runs could be re-requested."
    fi
  else
    local action classification
    action="$(jq -r '.recommended_action' "${result_file}")"
    classification="$(jq -r '.classification' "${result_file}")"
    if [[ "${action}" == "retry" ]]; then
      retry_note="**Retry:** skipped (classification=${classification}, retries_used=${retries_used}, max=${MAX_FLAKE_RETRIES}, min_confidence=${MIN_RETRY_CONFIDENCE})."
    fi
  fi

  # 3) Build and post sticky diagnosis comment (includes updated retries marker)
  local body new_retries
  body="$(jq -r '.pr_comment_markdown' "${result_file}")"
  if [[ -z "${body}" || "${body}" == "null" ]]; then
    echo "::error::Result missing pr_comment_markdown"
    exit 1
  fi
  new_retries="${retries_used}"
  [[ "${did_retry}" == "true" ]] && new_retries=$((retries_used + 1))

  body_file="$(mktemp)"
  {
    printf '%s\n' "${body}"
    [[ -n "${retry_note}" ]] && printf '\n---\n%s\n' "${retry_note}"
    printf '\n<!-- fullsend:ci-diagnose-retries:%s -->\n' "${new_retries}"
  } >"${body_file}"
  echo "::notice::Posting diagnosis comment on ${GITHUB_ISSUE_URL}"
  post_sticky_comment "${body_file}"
  rm -f "${body_file}"
  echo "::notice::ci-diagnose post-script complete"
}

main "$@"
