#!/usr/bin/env bash
# Generated by Cursor
# pre-ci-diagnose.sh — Collect failing GitHub Checks for a PR into check-context.json.
#
# Runs on the trusted runner before the sandbox starts.
#
# Required env:
#   REPO_FULL_NAME     — owner/repo (set by dispatch)
#   GH_TOKEN           — GitHub token with pull-requests:read, checks:read, and
#                        actions:read. Fine-grained PATs do not need Issues
#                        permission; retry markers are read via `gh pr view`.
#   GITHUB_ISSUE_URL   — PR URL (e.g. https://github.com/owner/repo/pull/123)
#   MAX_FLAKE_RETRIES  — retry budget recorded in context (set by harness yaml)
#   CHECK_CONTEXT_FILE — output path (set by harness yaml)
#
# Optional env:
#   OUTPUT_TEXT_MAX     — max chars of check output text to keep (default: 4000)
#   LOG_EXCERPT_MAX     — max chars per workflow run log excerpt (default: 8000)
set -euo pipefail

load_pr_from_url() {
  local json
  echo "::notice::Loading PR from ${GITHUB_ISSUE_URL}"
  json="$(gh pr view "${GITHUB_ISSUE_URL}" --json number,url,title,headRefOid,headRefName,baseRefName)"
  PR_NUMBER="$(jq -r '.number' <<<"${json}")"
  PR_URL="$(jq -r '.url' <<<"${json}")"
  PR_TITLE="$(jq -r '.title' <<<"${json}")"
  PR_HEAD_REF="$(jq -r '.headRefName' <<<"${json}")"
  PR_BASE_REF="$(jq -r '.baseRefName' <<<"${json}")"
  HEAD_SHA="$(jq -r '.headRefOid' <<<"${json}")"
  if [[ -z "${HEAD_SHA}" || "${HEAD_SHA}" == "null" ]]; then
    echo "::error::Failed to resolve HEAD_SHA from ${GITHUB_ISSUE_URL}"
    exit 1
  fi
  export PR_NUMBER PR_URL PR_TITLE PR_HEAD_REF PR_BASE_REF HEAD_SHA
}

# Read the highest <!-- fullsend:ci-diagnose-retries:N --> marker from PR
# conversation comments so the agent knows how many flake retries were used.
# Uses `gh pr view` (Pull Requests API). The Issues comments REST endpoint
# 404s for fine-grained PATs that have pull-requests:read but not Issues.
read_retries_used() {
  local max_seen api_output
  if api_output="$(
    gh pr view "${GITHUB_ISSUE_URL}" --json comments --jq '
      [.comments[].body // empty
        | strings
        | capture("<!-- fullsend:ci-diagnose-retries:(?<n>[0-9]+) -->")?
        | .n
        | tonumber
      ]
      | if length == 0 then 0 else max end
    '
  )"; then
    max_seen="$(printf '%s' "${api_output}" | tr -d '[:space:]')"
    if [[ "${max_seen}" =~ ^[0-9]+$ ]]; then
      printf '%s' "${max_seen}"
      return 0
    fi
    echo "::warning::Unexpected non-integer retries value: '${max_seen}'; defaulting retries_used=0" >&2
    printf '0'
    return 0
  fi
  echo "::warning::Failed to read PR comments for retry tracking; defaulting retries_used=0" >&2
  printf '0'
}

# List check runs for HEAD_SHA, keep only real failures, and write a trimmed
# JSON array the agent can consume (skips / dispatch jobs are excluded).
collect_failing_check_runs() {
  local raw_path="$1"
  local out_path="$2"
  local max_text="${OUTPUT_TEXT_MAX:-4000}"

  if ! gh api --paginate "repos/${REPO_FULL_NAME}/commits/${HEAD_SHA}/check-runs" \
    --jq '.check_runs[]' >"${raw_path}"; then
    echo "::error::Failed to list check runs for ${REPO_FULL_NAME}@${HEAD_SHA}"
    exit 1
  fi

  if [[ ! -s "${raw_path}" ]]; then
    echo '[]' >"${out_path}"
    return 0
  fi

  # Exclude skipped conclusions and Fullsend orchestration jobs (dispatch / …).
  # Those are agent-stage routing, not project CI — role-gated skips must not
  # surface as failing checks for the diagnose agent.
  jq -s --argjson max_text "${max_text}" '
    map(select(
      .conclusion != null and (
        .conclusion == "failure"
        or .conclusion == "timed_out"
        or .conclusion == "cancelled"
        or .conclusion == "action_required"
        or .conclusion == "startup_failure"
      )
      and (.name | test("^dispatch / ") | not)
    ))
    | map({
        check_name: .name,
        check_run_id: .id,
        conclusion: .conclusion,
        status: .status,
        details_url: (.details_url // null),
        html_url: (.html_url // null),
        started_at: (.started_at // null),
        completed_at: (.completed_at // null),
        app_slug: (.app.slug // null),
        output_title: (.output.title // null),
        output_summary: (.output.summary // null),
        output_text: (
          if (.output.text // null) == null then null
          elif (.output.text | length) <= $max_text then .output.text
          else (.output.text[0:$max_text] + "\n…[truncated]")
          end
        )
      })
  ' "${raw_path}" >"${out_path}"
}

# Collect legacy commit statuses in failure/error state (non-Check-Runs CI).
# Soft-fails to [] so a status API issue does not abort context collection.
collect_failing_statuses() {
  local out_path="$1"
  gh api "repos/${REPO_FULL_NAME}/commits/${HEAD_SHA}/status" \
    --jq '
      [.statuses[]
        | select(.state == "failure" or .state == "error")
        | {
            context: .context,
            state: .state,
            description: (.description // null),
            target_url: (.target_url // null),
            created_at: (.created_at // null),
            updated_at: (.updated_at // null)
          }
      ]
    ' >"${out_path}" 2>&1 || {
    echo "::warning::Failed to fetch commit statuses; defaulting to empty"
    echo '[]' >"${out_path}"
  }
}

# Pull truncated failed-job logs for each unique Actions run ID found in the
# failing checks' details/html URLs.
fetch_workflow_logs() {
  local checks_path="$1"
  local logs_dir="$2"
  local max_log_chars="${LOG_EXCERPT_MAX:-8000}"

  mkdir -p "${logs_dir}"

  local run_ids
  run_ids="$(jq -r '
    [.[]
      | select(.details_url != null or .html_url != null)
      | (.details_url // .html_url)
      | capture("actions/runs/(?<run_id>[0-9]+)")?
      | .run_id
    ] | unique[]
  ' "${checks_path}")" || true

  if [[ -z "${run_ids}" ]]; then
    echo "::notice::No workflow run IDs found in failing checks; skipping log fetch"
    return 0
  fi

  local count=0
  while IFS= read -r run_id; do
    [[ -z "${run_id}" ]] && continue
    local log_file="${logs_dir}/${run_id}.txt"
    echo "::notice::Fetching failed logs for run ${run_id}"
    if gh run view "${run_id}" --repo "${REPO_FULL_NAME}" --log-failed 2>/dev/null \
        | tail -c "${max_log_chars}" >"${log_file}"; then
      if [[ ! -s "${log_file}" ]]; then
        echo "(no failed-job log output)" >"${log_file}"
      fi
      count=$((count + 1))
    else
      echo "(log fetch failed or no logs available)" >"${log_file}"
    fi
  done <<< "${run_ids}"

  echo "::notice::Fetched logs for ${count} workflow run(s)"
}

# Assemble the final check-context.json: PR metadata, failing checks/statuses,
# workflow log excerpts, and the flake retry budget for the agent + post-script.
write_check_context() {
  local checks_path="$1"
  local statuses_path="$2"
  local retries_used="$3"
  local logs_dir="$4"
  local max_retries="${MAX_FLAKE_RETRIES}"
  local logs_json

  logs_json="$(
    find "${logs_dir}" -name '*.txt' -print0 \
      | xargs -0 -I{} sh -c 'printf "%s\t%s\n" "$(basename "$1" .txt)" "$(cat "$1")"' _ {} \
      | jq -Rn '[inputs | split("\t") | {(.[0]): .[1]}] | add // {}'
  )"

  jq -n \
    --arg repo "${REPO_FULL_NAME}" \
    --argjson pr_number "${PR_NUMBER}" \
    --arg sha "${HEAD_SHA}" \
    --arg pr_url "${PR_URL}" \
    --arg pr_title "${PR_TITLE}" \
    --arg head_ref "${PR_HEAD_REF}" \
    --arg base_ref "${PR_BASE_REF}" \
    --arg collected_at "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
    --argjson retries_used "${retries_used}" \
    --argjson max_retries "${max_retries}" \
    --slurpfile checks "${checks_path}" \
    --slurpfile statuses "${statuses_path}" \
    --argjson logs "${logs_json}" '
    {
      repo_full_name: $repo,
      pr_number: $pr_number,
      head_sha: $sha,
      pr_url: $pr_url,
      pr_title: $pr_title,
      head_ref: $head_ref,
      base_ref: $base_ref,
      collected_at: $collected_at,
      failing_checks: $checks[0],
      failing_statuses: $statuses[0],
      workflow_logs: $logs,
      retry_budget: {
        max_flake_retries: $max_retries,
        retries_used: $retries_used,
        retries_remaining: (if ($max_retries - $retries_used) > 0 then ($max_retries - $retries_used) else 0 end)
      }
    }
  ' >"${CHECK_CONTEXT_FILE}"
}

main() {
  command -v gh >/dev/null || { echo "::error::gh not found"; exit 1; }
  command -v jq >/dev/null || { echo "::error::jq not found"; exit 1; }
  : "${REPO_FULL_NAME:?Required env REPO_FULL_NAME is not set}"
  : "${GH_TOKEN:?Required env GH_TOKEN is not set}"
  : "${GITHUB_ISSUE_URL:?Required env GITHUB_ISSUE_URL is not set}"
  export GH_TOKEN

  CHECK_CONTEXT_FILE="${CHECK_CONTEXT_FILE}"
  mkdir -p "$(dirname "${CHECK_CONTEXT_FILE}")"

  # 1) Pin to current PR head via `gh pr view` (URL)
  load_pr_from_url

  echo "::notice::Collecting failing checks for ${REPO_FULL_NAME}#${PR_NUMBER} @ ${HEAD_SHA}"

  local raw_checks checks_json statuses_json logs_dir retries_used failing_count
  raw_checks="$(mktemp)"
  checks_json="$(mktemp)"
  statuses_json="$(mktemp)"
  logs_dir="$(mktemp -d)"

  # 2) Gather failure signals + logs, then record retry history from PR comments
  collect_failing_check_runs "${raw_checks}" "${checks_json}"
  collect_failing_statuses "${statuses_json}"
  fetch_workflow_logs "${checks_json}" "${logs_dir}"
  retries_used="$(read_retries_used)"

  # 3) Write the agent input context and clean up temps
  write_check_context "${checks_json}" "${statuses_json}" "${retries_used}" "${logs_dir}"

  failing_count="$(jq 'length' "${checks_json}")"
  echo "::notice::Wrote ${CHECK_CONTEXT_FILE} (${failing_count} failing check runs; retries_used=${retries_used})"
  echo "::group::${CHECK_CONTEXT_FILE}"
  jq . "${CHECK_CONTEXT_FILE}"
  echo "::endgroup::"

  rm -f "${raw_checks}" "${checks_json}" "${statuses_json}"
  rm -rf "${logs_dir}"
}

main "$@"
