#!/usr/bin/env bash
# Generated by Cursor
# Validate agent output against schemas/ci-diagnose-result.schema.json.
#
# Mirrors fullsend-ai/agents validate-output-schema.sh path resolution:
# working directory is the iteration dir; result lives under output/.
#
# Required env:
#   FULLSEND_OUTPUT_SCHEMA — path to the JSON Schema file
#   FULLSEND_OUTPUT_FILE — filename to validate (set by harness yaml)
set -euo pipefail

: "${FULLSEND_OUTPUT_SCHEMA:?FULLSEND_OUTPUT_SCHEMA must be set}"
: "${FULLSEND_OUTPUT_FILE:?Required env FULLSEND_OUTPUT_FILE is not set}"

OUTPUT_DIR="output"
if [[ ! -d "${OUTPUT_DIR}" ]]; then
  echo "::error::output directory not found"
  exit 1
fi

_output_file="${FULLSEND_OUTPUT_FILE}"
_output_file="$(basename "${_output_file}")"
RESULT_FILE="${OUTPUT_DIR}/${_output_file}"

if [[ ! -f "${RESULT_FILE}" ]]; then
  echo "::error::Result file not found: ${RESULT_FILE}"
  exit 1
fi

echo "::notice::Validating ${RESULT_FILE} against ${FULLSEND_OUTPUT_SCHEMA}"

if ! jq empty "${RESULT_FILE}" >/dev/null 2>&1; then
  echo "::error::Result is not valid JSON: ${RESULT_FILE}"
  exit 1
fi

if command -v check-jsonschema >/dev/null 2>&1; then
  check-jsonschema --schemafile "${FULLSEND_OUTPUT_SCHEMA}" "${RESULT_FILE}"
  exit $?
fi

if command -v ajv >/dev/null 2>&1; then
  ajv validate -s "${FULLSEND_OUTPUT_SCHEMA}" -d "${RESULT_FILE}"
  exit $?
fi

if python3 -c "import jsonschema" 2>/dev/null; then
  python3 -c "
import json, sys
from jsonschema import validate, ValidationError

with open(sys.argv[1]) as f:
    instance = json.load(f)
with open(sys.argv[2]) as f:
    schema = json.load(f)
try:
    validate(instance=instance, schema=schema)
    print('PASS: output validated against schema')
except ValidationError as e:
    print(f'FAIL: schema validation error: {e.message}')
    if e.path:
        print(f'  at: {\".\".join(str(p) for p in e.path)}')
    sys.exit(1)
" "${RESULT_FILE}" "${FULLSEND_OUTPUT_SCHEMA}"
  exit $?
fi

# Soft fallback: structural presence of required top-level keys.
required=(status classification confidence recommended_action failures retry_targets pr_comment_markdown reasoning)
for key in "${required[@]}"; do
  if [[ "$(jq -r --arg k "${key}" 'has($k)' "${RESULT_FILE}")" != "true" ]]; then
    echo "::error::Result missing required key: ${key}"
    exit 1
  fi
done

echo "::notice::Schema tools unavailable; required-key check passed for ${RESULT_FILE}"
exit 0
