# Generated by Cursor
#!/usr/bin/env bash
# Mock gh CLI that returns canned responses from PR #8 fixtures.
# Placed at the front of PATH to intercept all `gh` calls.
set -euo pipefail

FIXTURE_DIR="$(cd "$(dirname "$0")" && pwd)"

case "$1" in
  pr)
    # gh pr view <url> --json <fields> --jq <expr>
    if [[ "${2:-}" == "view" ]]; then
      shift 2
      url=""
      json_fields=""
      jq_expr=""
      while [[ $# -gt 0 ]]; do
        case "$1" in
          --json)  json_fields="$2"; shift 2 ;;
          --jq)    jq_expr="$2"; shift 2 ;;
          -*)      shift ;;
          *)       url="$1"; shift ;;
        esac
      done

      if [[ "${json_fields}" == *"comments"* ]]; then
        if [[ -n "${jq_expr}" ]]; then
          jq -r "${jq_expr}" "${FIXTURE_DIR}/pr8-pr-comments.json"
        else
          cat "${FIXTURE_DIR}/pr8-pr-comments.json"
        fi
      else
        if [[ -n "${jq_expr}" ]]; then
          jq -r "${jq_expr}" "${FIXTURE_DIR}/pr8-pr-view.json"
        else
          cat "${FIXTURE_DIR}/pr8-pr-view.json"
        fi
      fi
      exit 0
    fi
    ;;

  api)
    shift
    endpoint=""
    jq_expr=""
    paginate=false
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --jq)       jq_expr="$2"; shift 2 ;;
        --paginate) paginate=true; shift ;;
        -*)         shift ;;
        *)          endpoint="$1"; shift ;;
      esac
    done

    if [[ "${endpoint}" == *"/check-runs" ]]; then
      if [[ -n "${jq_expr}" ]]; then
        jq -r "${jq_expr}" "${FIXTURE_DIR}/pr8-check-runs.json"
      else
        cat "${FIXTURE_DIR}/pr8-check-runs.json"
      fi
      exit 0
    fi

    if [[ "${endpoint}" == *"/status" ]]; then
      if [[ -n "${jq_expr}" ]]; then
        jq -r "${jq_expr}" "${FIXTURE_DIR}/pr8-status.json"
      else
        cat "${FIXTURE_DIR}/pr8-status.json"
      fi
      exit 0
    fi

    echo "gh-mock: unhandled api endpoint: ${endpoint}" >&2
    exit 1
    ;;

  run)
    # gh run view <run_id> --repo <repo> --log-failed
    shift
    if [[ "${1:-}" == "view" ]]; then
      shift
      run_id="$1"; shift
      while [[ $# -gt 0 ]]; do
        case "$1" in
          --repo)       shift 2 ;;
          --log-failed) shift ;;
          *)            shift ;;
        esac
      done

      log_file="${FIXTURE_DIR}/pr8-log-${run_id}.txt"
      if [[ -f "${log_file}" ]]; then
        cat "${log_file}"
      else
        echo ""
      fi
      exit 0
    fi
    ;;

  *)
    echo "gh-mock: unhandled command: $*" >&2
    exit 1
    ;;
esac
