#!/usr/bin/env bash
# Generated by Cursor
# post-ci-diagnose.sh — Post diagnosis comment and optionally re-run flaky checks.
#
# Runs on the trusted runner after sandbox exit. Side effects (comments, retries)
# happen here — never inside the sandbox.
#
# Required env:
#   REPO_FULL_NAME — owner/repo
#   PR_NUMBER      — pull request number
#   GH_TOKEN       — GitHub token with pull-requests:write and checks:write
#
# Optional env:
#   CHECK_CONTEXT_FILE     — pre-script context (default: /tmp/workspace/check-context.json)
#   FULLSEND_OUTPUT_FILE   — result filename (default: ci-diagnose-result.json)
#   MAX_FLAKE_RETRIES      — max automatic flake retries (default: 1)
#   MIN_RETRY_CONFIDENCE   — minimum confidence to retry (default: 0.7)
set -euo pipefail

COMMENT_MARKER='<!-- fullsend:ci-diagnose -->'
RESULT_NAME="${FULLSEND_OUTPUT_FILE:-ci-diagnose-result.json}"

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "::error::Required command not found: $1"
    exit 1
  fi
}

require_env() {
  local name="$1"
  if [[ -z "${!name:-}" ]]; then
    echo "::error::Required environment variable not set: ${name}"
    exit 1
  fi
}

find_result_file() {
  local candidate
  if [[ -n "${FULLSEND_VALIDATED_ITERATION_DIR:-}" ]]; then
    for candidate in \
      "${FULLSEND_VALIDATED_ITERATION_DIR}/${RESULT_NAME}" \
      "${FULLSEND_VALIDATED_ITERATION_DIR}/output/${RESULT_NAME}" \
      "${FULLSEND_VALIDATED_ITERATION_DIR}/agent-result.json" \
      "${FULLSEND_VALIDATED_ITERATION_DIR}/result.json"
    do
      if [[ -f "${candidate}" ]]; then
        printf '%s' "${candidate}"
        return 0
      fi
    done
    echo "::error::FULLSEND_VALIDATED_ITERATION_DIR set but result not found"
    exit 1
  fi

  if [[ -n "${FULLSEND_OUTPUT_DIR:-}" && -f "${FULLSEND_OUTPUT_DIR}/${RESULT_NAME}" ]]; then
    printf '%s' "${FULLSEND_OUTPUT_DIR}/${RESULT_NAME}"
    return 0
  fi

  local found=""
  for candidate in iteration-*/output/"${RESULT_NAME}" iteration-*/"${RESULT_NAME}"; do
    if [[ -f "${candidate}" ]]; then
      found="${candidate}"
    fi
  done
  if [[ -n "${found}" ]]; then
    printf '%s' "${found}"
    return 0
  fi

  echo "::error::Result file ${RESULT_NAME} not found in iteration output"
  exit 1
}

retries_used_from_context() {
  local context_file="${CHECK_CONTEXT_FILE:-/tmp/workspace/check-context.json}"
  if [[ -f "${context_file}" ]]; then
    jq -r '.retry_budget.retries_used // 0' "${context_file}"
    return 0
  fi
  printf '0'
}

should_retry() {
  local result_file="$1"
  local retries_used="$2"
  local max_retries="${MAX_FLAKE_RETRIES:-1}"
  local min_confidence="${MIN_RETRY_CONFIDENCE:-0.7}"

  jq -e \
    --argjson retries_used "${retries_used}" \
    --argjson max_retries "${max_retries}" \
    --argjson min_confidence "${min_confidence}" '
      .recommended_action == "retry"
      and .classification == "flaky"
      and (.confidence >= $min_confidence)
      and ($retries_used < $max_retries)
      and ((.retry_targets | length) > 0)
    ' "${result_file}" >/dev/null 2>&1
}

build_comment_body() {
  local result_file="$1"
  local retries_used="$2"
  local did_retry="$3"
  local retry_note="$4"
  local new_retries="${retries_used}"
  local body

  if [[ "${did_retry}" == "true" ]]; then
    new_retries=$((retries_used + 1))
  fi

  body="$(jq -r '.pr_comment_markdown' "${result_file}")"
  if [[ -z "${body}" || "${body}" == "null" ]]; then
    echo "::error::Result missing pr_comment_markdown"
    exit 1
  fi

  {
    printf '%s\n' "${body}"
    if [[ -n "${retry_note}" ]]; then
      printf '\n---\n%s\n' "${retry_note}"
    fi
    printf '\n<!-- fullsend:ci-diagnose-retries:%s -->\n' "${new_retries}"
  }
}

post_sticky_comment() {
  local body_file="$1"
  local token="${GH_TOKEN}"
  export GITHUB_TOKEN="${token}"

  if command -v fullsend >/dev/null 2>&1; then
    fullsend post-comment \
      --repo "${REPO_FULL_NAME}" \
      --number "${PR_NUMBER}" \
      --marker "${COMMENT_MARKER}" \
      --token "${token}" \
      --result "${body_file}"
    return 0
  fi

  echo "::warning::fullsend CLI unavailable; posting a non-sticky PR comment"
  gh pr comment "${PR_NUMBER}" --repo "${REPO_FULL_NAME}" --body-file "${body_file}"
}

rerequest_targets() {
  local result_file="$1"
  local id name err_output
  local ok_count=0
  local fail_count=0

  while IFS=$'\t' read -r id name; do
    if [[ -z "${id}" || "${id}" == "null" ]]; then
      echo "::warning::Skipping retry target without check_run_id: ${name}"
      fail_count=$((fail_count + 1))
      continue
    fi
    echo "::notice::Re-requesting check run ${id} (${name})"
    if err_output="$(gh api -X POST "repos/${REPO_FULL_NAME}/check-runs/${id}/rerequest" 2>&1)"; then
      ok_count=$((ok_count + 1))
    else
      echo "::warning::Failed to re-request check run ${id} (${name}): ${err_output}"
      fail_count=$((fail_count + 1))
    fi
  done < <(jq -r '.retry_targets[] | [(.check_run_id // "null")|tostring, .check_name] | @tsv' "${result_file}")

  echo "::notice::Retry summary: ok=${ok_count} failed=${fail_count}"
  if [[ "${ok_count}" -eq 0 ]]; then
    return 1
  fi
  return 0
}

main() {
  require_cmd gh
  require_cmd jq
  require_env REPO_FULL_NAME
  require_env PR_NUMBER
  require_env GH_TOKEN
  export GH_TOKEN

  local result_file retries_used did_retry retry_note body_file
  result_file="$(find_result_file)"
  echo "::notice::Reading diagnosis result from ${result_file}"

  if ! jq empty "${result_file}" >/dev/null 2>&1; then
    echo "::error::Result is not valid JSON: ${result_file}"
    exit 1
  fi

  retries_used="$(retries_used_from_context)"
  retries_used="$(printf '%s' "${retries_used}" | tr -d '[:space:]')"
  if [[ ! "${retries_used}" =~ ^[0-9]+$ ]]; then
    retries_used=0
  fi

  did_retry="false"
  retry_note=""

  if should_retry "${result_file}" "${retries_used}"; then
    if rerequest_targets "${result_file}"; then
      did_retry="true"
      retry_note="**Retry:** re-requested flaky check run(s) (attempt $((retries_used + 1))/${MAX_FLAKE_RETRIES:-1})."
    else
      retry_note="**Retry:** recommended, but no check runs could be re-requested."
    fi
  else
    local action classification
    action="$(jq -r '.recommended_action' "${result_file}")"
    classification="$(jq -r '.classification' "${result_file}")"
    if [[ "${action}" == "retry" ]]; then
      retry_note="**Retry:** skipped (classification=${classification}, retries_used=${retries_used}, max=${MAX_FLAKE_RETRIES:-1}, min_confidence=${MIN_RETRY_CONFIDENCE:-0.7})."
    fi
  fi

  body_file="$(mktemp)"
  build_comment_body "${result_file}" "${retries_used}" "${did_retry}" "${retry_note}" >"${body_file}"
  echo "::notice::Posting diagnosis comment on ${REPO_FULL_NAME}#${PR_NUMBER}"
  post_sticky_comment "${body_file}"
  rm -f "${body_file}"
  echo "::notice::ci-diagnose post-script complete"
}

main "$@"
