#!/usr/bin/env bash
# Generated by Cursor
# Placeholder post-script for ci-diagnose (GitHub).
# TODO(pre-post-scripts): post PR comment and bounded flake retry from result JSON.
set -euo pipefail

echo "::error::scripts/post-ci-diagnose.sh is not implemented yet"
exit 1
