#!/usr/bin/env bash
# Generated by Cursor
# pre-ci-diagnose.sh — Collect failing GitHub Checks for a PR into check-context.json.
#
# Runs on the trusted runner before the sandbox starts.
#
# Required env:
#   REPO_FULL_NAME — owner/repo
#   PR_NUMBER      — pull request number
#   GH_TOKEN       — GitHub token with checks:read (and pull-requests:read)
#
# Optional env:
#   HEAD_SHA            — PR head SHA (resolved from the PR when unset)
#   CHECK_CONTEXT_FILE  — output path (default: /tmp/workspace/check-context.json)
#   MAX_FLAKE_RETRIES   — retry budget recorded in context (default: 1)
#   OUTPUT_TEXT_MAX     — max chars of check output text to keep (default: 4000)
set -euo pipefail

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "::error::Required command not found: $1"
    exit 1
  fi
}

require_env() {
  local name="$1"
  if [[ -z "${!name:-}" ]]; then
    echo "::error::Required environment variable not set: ${name}"
    exit 1
  fi
}

resolve_head_sha() {
  if [[ -n "${HEAD_SHA:-}" ]]; then
    return 0
  fi
  echo "::notice::HEAD_SHA unset; resolving from PR #${PR_NUMBER}"
  HEAD_SHA="$(gh api "repos/${REPO_FULL_NAME}/pulls/${PR_NUMBER}" --jq '.head.sha')"
  if [[ -z "${HEAD_SHA}" || "${HEAD_SHA}" == "null" ]]; then
    echo "::error::Failed to resolve HEAD_SHA for ${REPO_FULL_NAME}#${PR_NUMBER}"
    exit 1
  fi
  export HEAD_SHA
}

read_retries_used() {
  local max_seen api_output
  api_output="$(
    gh api --paginate "repos/${REPO_FULL_NAME}/issues/${PR_NUMBER}/comments" \
      --jq '
        [.[].body
          | capture("<!-- fullsend:ci-diagnose-retries:(?<n>[0-9]+) -->")?
          | .n
          | tonumber
        ]
        | if length == 0 then 0 else max end
      '
  )" || {
    echo "::error::Failed to read PR comments for retry tracking on ${REPO_FULL_NAME}#${PR_NUMBER}"
    exit 1
  }
  # Normalize multi-line / empty API noise to a single integer.
  max_seen="$(printf '%s' "${api_output}" | tr -d '[:space:]')"
  if [[ ! "${max_seen}" =~ ^[0-9]+$ ]]; then
    echo "::error::Unexpected non-integer retries value: '${max_seen}'"
    exit 1
  fi
  printf '%s' "${max_seen}"
}

collect_failing_check_runs() {
  local raw_path="$1"
  local out_path="$2"
  local max_text="${OUTPUT_TEXT_MAX:-4000}"

  if ! gh api --paginate "repos/${REPO_FULL_NAME}/commits/${HEAD_SHA}/check-runs" \
    --jq '.check_runs[]' >"${raw_path}"; then
    echo "::error::Failed to list check runs for ${REPO_FULL_NAME}@${HEAD_SHA}"
    exit 1
  fi

  if [[ ! -s "${raw_path}" ]]; then
    echo '[]' >"${out_path}"
    return 0
  fi

  jq -s --argjson max_text "${max_text}" '
    map(select(
      .conclusion != null and (
        .conclusion == "failure"
        or .conclusion == "timed_out"
        or .conclusion == "cancelled"
        or .conclusion == "action_required"
        or .conclusion == "startup_failure"
      )
    ))
    | map({
        check_name: .name,
        check_run_id: .id,
        conclusion: .conclusion,
        status: .status,
        details_url: (.details_url // null),
        html_url: (.html_url // null),
        started_at: (.started_at // null),
        completed_at: (.completed_at // null),
        app_slug: (.app.slug // null),
        output_title: (.output.title // null),
        output_summary: (.output.summary // null),
        output_text: (
          if (.output.text // null) == null then null
          elif (.output.text | length) <= $max_text then .output.text
          else (.output.text[0:$max_text] + "\n…[truncated]")
          end
        )
      })
  ' "${raw_path}" >"${out_path}"
}

collect_failing_statuses() {
  local out_path="$1"
  gh api "repos/${REPO_FULL_NAME}/commits/${HEAD_SHA}/status" \
    --jq '
      [.statuses[]
        | select(.state == "failure" or .state == "error")
        | {
            context: .context,
            state: .state,
            description: (.description // null),
            target_url: (.target_url // null),
            created_at: (.created_at // null),
            updated_at: (.updated_at // null)
          }
      ]
    ' >"${out_path}" 2>/dev/null || echo '[]' >"${out_path}"
}

write_check_context() {
  local checks_path="$1"
  local statuses_path="$2"
  local retries_used="$3"
  local max_retries="${MAX_FLAKE_RETRIES:-1}"
  local tmp_pr

  tmp_pr="$(mktemp)"
  gh api "repos/${REPO_FULL_NAME}/pulls/${PR_NUMBER}" >"${tmp_pr}"

  jq -n \
    --arg repo "${REPO_FULL_NAME}" \
    --argjson pr_number "${PR_NUMBER}" \
    --arg sha "${HEAD_SHA}" \
    --arg collected_at "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
    --argjson retries_used "${retries_used}" \
    --argjson max_retries "${max_retries}" \
    --slurpfile pr_json "${tmp_pr}" \
    --slurpfile checks "${checks_path}" \
    --slurpfile statuses "${statuses_path}" '
    {
      repo_full_name: $repo,
      pr_number: $pr_number,
      head_sha: $sha,
      pr_url: $pr_json[0].html_url,
      pr_title: $pr_json[0].title,
      head_ref: $pr_json[0].head.ref,
      base_ref: $pr_json[0].base.ref,
      collected_at: $collected_at,
      failing_checks: $checks[0],
      failing_statuses: $statuses[0],
      retry_budget: {
        max_flake_retries: $max_retries,
        retries_used: $retries_used,
        retries_remaining: (if ($max_retries - $retries_used) > 0 then ($max_retries - $retries_used) else 0 end)
      }
    }
  ' >"${CHECK_CONTEXT_FILE}"

  rm -f "${tmp_pr}"
}

main() {
  require_cmd gh
  require_cmd jq
  require_env REPO_FULL_NAME
  require_env PR_NUMBER
  require_env GH_TOKEN
  export GH_TOKEN

  CHECK_CONTEXT_FILE="${CHECK_CONTEXT_FILE:-/tmp/workspace/check-context.json}"
  mkdir -p "$(dirname "${CHECK_CONTEXT_FILE}")"

  resolve_head_sha

  echo "::notice::Collecting failing checks for ${REPO_FULL_NAME}#${PR_NUMBER} @ ${HEAD_SHA}"

  local raw_checks checks_json statuses_json retries_used failing_count
  raw_checks="$(mktemp)"
  checks_json="$(mktemp)"
  statuses_json="$(mktemp)"

  collect_failing_check_runs "${raw_checks}" "${checks_json}"
  collect_failing_statuses "${statuses_json}"
  retries_used="$(read_retries_used)"
  write_check_context "${checks_json}" "${statuses_json}" "${retries_used}"

  failing_count="$(jq 'length' "${checks_json}")"
  echo "::notice::Wrote ${CHECK_CONTEXT_FILE} (${failing_count} failing check runs; retries_used=${retries_used})"

  rm -f "${raw_checks}" "${checks_json}" "${statuses_json}"
}

main "$@"
