#!/usr/bin/env bash
# Generated by Cursor
# Minimal JSON Schema validation helper for the harness validation_loop.
# Prefers ajv-cli or check-jsonschema when available; falls back to jq parse check.
set -euo pipefail

SCHEMA="${FULLSEND_OUTPUT_SCHEMA:-}"
RESULT="${FULLSEND_OUTPUT_FILE:-}"
OUTPUT_DIR="${FULLSEND_OUTPUT_DIR:-/sandbox/workspace/output}"

if [[ -z "${RESULT}" ]]; then
  RESULT="${OUTPUT_DIR}/ci-diagnose-result.json"
fi

if [[ ! -f "${RESULT}" ]]; then
  echo "::error::Result file not found: ${RESULT}"
  exit 1
fi

if [[ -z "${SCHEMA}" || ! -f "${SCHEMA}" ]]; then
  echo "::error::Schema file not found: ${SCHEMA:-<unset>}"
  exit 1
fi

if ! jq empty "${RESULT}" >/dev/null 2>&1; then
  echo "::error::Result is not valid JSON: ${RESULT}"
  exit 1
fi

if command -v check-jsonschema >/dev/null 2>&1; then
  check-jsonschema --schemafile "${SCHEMA}" "${RESULT}"
  exit $?
fi

if command -v ajv >/dev/null 2>&1; then
  ajv validate -s "${SCHEMA}" -d "${RESULT}"
  exit $?
fi

# Soft fallback: structural presence of required top-level keys.
required=(status classification confidence recommended_action failures retry_targets pr_comment_markdown reasoning)
for key in "${required[@]}"; do
  if [[ "$(jq -r --arg k "${key}" 'has($k)' "${RESULT}")" != "true" ]]; then
    echo "::error::Result missing required key: ${key}"
    exit 1
  fi
done

echo "::notice::Schema tools unavailable; required-key check passed for ${RESULT}"
exit 0
