# Generated by Cursor
"""Test pre-ci-diagnose.sh against canned PR #8 data.

Simulates the state when both infra-pull and flaky-unit were failing,
with one retry already consumed.  Uses the bash gh-mock.sh shim that
returns fixture data instead of calling the real GitHub API.

Run:
    python3 .fullsend/tests/pre-ci-diagnose/test_pr8.py
"""
from __future__ import annotations

import json
import os
import shutil
import stat
import subprocess
import tempfile
import textwrap
import unittest
from pathlib import Path

TEST_DIR = Path(__file__).resolve().parent
REPO_ROOT = TEST_DIR.parents[2]
SCRIPT_UNDER_TEST = REPO_ROOT / ".fullsend" / "scripts" / "pre-ci-diagnose.sh"
FIXTURE_DIR = TEST_DIR / "fixtures"


class PreCiDiagnoseTest(unittest.TestCase):
    """End-to-end test: run pre-ci-diagnose.sh with mocked gh, validate output."""

    context: dict  # populated in setUpClass

    @classmethod
    def setUpClass(cls) -> None:
        cls.work_dir = Path(tempfile.mkdtemp(prefix="pre-ci-diagnose-test-"))
        cls.output_file = cls.work_dir / "check-context.json"

        mock_bin = cls.work_dir / "bin"
        mock_bin.mkdir()
        gh_wrapper = mock_bin / "gh"
        gh_wrapper.write_text(textwrap.dedent(f"""\
            #!/usr/bin/env bash
            exec "{FIXTURE_DIR / 'gh-mock.sh'}" "$@"
        """))
        gh_wrapper.chmod(gh_wrapper.stat().st_mode | stat.S_IEXEC)

        env = {
            **os.environ,
            "PATH": f"{mock_bin}:{os.environ['PATH']}",
            "REPO_FULL_NAME": "alice17/test-for-fullsend",
            "GH_TOKEN": "mock-token",
            "GITHUB_ISSUE_URL": "https://github.com/alice17/test-for-fullsend/pull/8",
            "CHECK_CONTEXT_FILE": str(cls.output_file),
            "MAX_FLAKE_RETRIES": "2",
        }

        result = subprocess.run(
            ["bash", str(SCRIPT_UNDER_TEST)],
            env=env,
            capture_output=True,
            text=True,
        )
        cls.script_stdout = result.stdout
        cls.script_stderr = result.stderr
        cls.script_rc = result.returncode

        if result.returncode != 0:
            raise RuntimeError(
                f"pre-script exited {result.returncode}\n"
                f"--- stdout ---\n{result.stdout}\n"
                f"--- stderr ---\n{result.stderr}"
            )

        with open(cls.output_file) as f:
            cls.context = json.load(f)

    @classmethod
    def tearDownClass(cls) -> None:
        shutil.rmtree(cls.work_dir, ignore_errors=True)

    # -- PR metadata ---------------------------------------------------------

    def test_repo_full_name(self) -> None:
        self.assertEqual(self.context["repo_full_name"], "alice17/test-for-fullsend")

    def test_pr_number(self) -> None:
        self.assertEqual(self.context["pr_number"], 8)

    def test_head_sha(self) -> None:
        self.assertEqual(
            self.context["head_sha"],
            "48e2e31dd67514b23a30ea965796200b63b8119a",
        )

    def test_pr_title(self) -> None:
        self.assertEqual(
            self.context["pr_title"],
            "Test fullsend custom agent is registered",
        )

    def test_head_ref(self) -> None:
        self.assertEqual(self.context["head_ref"], "test-branch")

    def test_base_ref(self) -> None:
        self.assertEqual(self.context["base_ref"], "main")

    def test_pr_url(self) -> None:
        self.assertEqual(
            self.context["pr_url"],
            "https://github.com/alice17/test-for-fullsend/pull/8",
        )

    def test_collected_at_is_iso8601(self) -> None:
        self.assertRegex(self.context["collected_at"], r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$")

    # -- Failing checks filtering -------------------------------------------

    def test_failing_checks_count(self) -> None:
        """infra-pull deduplicated + flaky-unit = 2 failing checks."""
        self.assertEqual(len(self.context["failing_checks"]), 2)

    def test_dispatch_checks_excluded(self) -> None:
        names = [c["check_name"] for c in self.context["failing_checks"]]
        for name in names:
            self.assertFalse(
                name.startswith("dispatch /"),
                f"dispatch job '{name}' should have been filtered out",
            )

    def test_check_names(self) -> None:
        names = sorted(c["check_name"] for c in self.context["failing_checks"])
        self.assertEqual(names, ["flaky-unit", "infra-pull"])

    # -- infra-pull deduplication --------------------------------------------

    def _infra_check(self) -> dict:
        return next(c for c in self.context["failing_checks"] if c["check_name"] == "infra-pull")

    def test_infra_pull_keeps_newer_run(self) -> None:
        self.assertEqual(self._infra_check()["check_run_id"], 95712166792)

    def test_infra_pull_completed_at(self) -> None:
        self.assertEqual(self._infra_check()["completed_at"], "2026-08-18T12:34:05Z")

    # -- flaky-unit check ----------------------------------------------------

    def _flaky_check(self) -> dict:
        return next(c for c in self.context["failing_checks"] if c["check_name"] == "flaky-unit")

    def test_flaky_unit_id(self) -> None:
        self.assertEqual(self._flaky_check()["check_run_id"], 95712166264)

    def test_flaky_unit_conclusion(self) -> None:
        self.assertEqual(self._flaky_check()["conclusion"], "failure")

    # -- Commit statuses -----------------------------------------------------

    def test_failing_statuses_empty(self) -> None:
        self.assertEqual(self.context["failing_statuses"], [])

    # -- Workflow logs -------------------------------------------------------

    def test_workflow_logs_present(self) -> None:
        self.assertIsInstance(self.context["workflow_logs"], dict)
        self.assertGreater(len(self.context["workflow_logs"]), 0)

    def test_workflow_logs_has_run_ids(self) -> None:
        """Run IDs extracted from check details_url should appear as keys."""
        log_keys = set(self.context["workflow_logs"].keys())
        self.assertIn("32137506657", log_keys, "missing infra-pull run log")
        self.assertIn("32137506523", log_keys, "missing flaky-unit run log")

    def test_workflow_logs_keys_are_only_run_ids(self) -> None:
        """Keys must be numeric run IDs — no spurious job-name keys."""
        for key in self.context["workflow_logs"]:
            self.assertRegex(key, r"^\d+$", f"unexpected non-numeric key: {key!r}")

    def test_workflow_logs_not_empty(self) -> None:
        for run_id, content in self.context["workflow_logs"].items():
            self.assertTrue(len(content) > 0, f"log for run {run_id} is empty")

    def test_workflow_logs_contain_multiline_content(self) -> None:
        """Values must be full log text, not single-field fragments."""
        for run_id, content in self.context["workflow_logs"].items():
            self.assertGreater(
                content.count("\n"), 1,
                f"log for run {run_id} should be multi-line, got: {content[:120]!r}",
            )

    def test_workflow_log_infra_pull_has_error(self) -> None:
        content = self.context["workflow_logs"]["32137506657"]
        self.assertIn("503 Service Unavailable", content)

    def test_workflow_log_flaky_unit_has_failure(self) -> None:
        content = self.context["workflow_logs"]["32137506523"]
        self.assertIn("FAIL src/widget.test.js", content)

    # -- Retry budget --------------------------------------------------------

    def test_max_flake_retries(self) -> None:
        self.assertEqual(self.context["retry_budget"]["max_flake_retries"], 2)

    def test_retries_per_check_keys(self) -> None:
        per_check = self.context["retry_budget"]["per_check"]
        self.assertEqual(sorted(per_check.keys()), ["flaky-unit", "infra-pull"])

    def test_retries_flaky_unit_used(self) -> None:
        """flaky-unit has a retry marker in the fixture comments."""
        budget = self.context["retry_budget"]["per_check"]["flaky-unit"]
        self.assertEqual(budget["retries_used"], 1)

    def test_retries_flaky_unit_remaining(self) -> None:
        budget = self.context["retry_budget"]["per_check"]["flaky-unit"]
        self.assertEqual(budget["retries_remaining"], 1)

    def test_retries_infra_pull_used(self) -> None:
        """infra-pull has no retry marker — fresh budget."""
        budget = self.context["retry_budget"]["per_check"]["infra-pull"]
        self.assertEqual(budget["retries_used"], 0)

    def test_retries_infra_pull_remaining(self) -> None:
        budget = self.context["retry_budget"]["per_check"]["infra-pull"]
        self.assertEqual(budget["retries_remaining"], 2)

    # -- Field completeness --------------------------------------------------

    EXPECTED_CHECK_FIELDS = {
        "check_name", "check_run_id", "conclusion", "status",
        "details_url", "html_url", "started_at", "completed_at",
        "app_slug",
    }

    def test_all_checks_have_required_fields(self) -> None:
        for check in self.context["failing_checks"]:
            missing = self.EXPECTED_CHECK_FIELDS - set(check.keys())
            self.assertFalse(
                missing,
                f"check '{check.get('check_name', '?')}' missing fields: {missing}",
            )

    # -- Top-level keys ------------------------------------------------------

    EXPECTED_TOP_KEYS = {
        "repo_full_name", "pr_number", "head_sha", "pr_url", "pr_title",
        "head_ref", "base_ref", "collected_at",
        "failing_checks", "failing_statuses", "workflow_logs", "retry_budget",
    }

    def test_top_level_keys(self) -> None:
        missing = self.EXPECTED_TOP_KEYS - set(self.context.keys())
        self.assertFalse(missing, f"missing top-level keys: {missing}")


if __name__ == "__main__":
    unittest.main(verbosity=2)
